require 'hoe'
require './lib/footballdata/version.rb'

Hoe.spec 'footballdata-api' do

  self.version = FootballdataApi::VERSION

  self.summary = "footballdata-api - get football data via Daniel Freitag's football-data.org api v4"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['tzinfo'],
    ['season-formats'], 
    ['webget'],    
    ['cocos'],  ## later pull in with sportsdb-writers
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
