require 'hoe'
require './lib/webget-football/version.rb'

Hoe.spec 'webget-football' do

  self.version = Webget::Module::Football::VERSION

  self.summary = 'webget-football - get football data via web pages or web api (json) calls'
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
