require 'hoe'
## require './lib/fbtxt-pp/version.rb'

Hoe.spec 'fbtxt-pp' do

  self.version = '0.0.1'

  self.summary = "fbtxt-pp - pretty print (pp) football match fixtures & results in the football.txt format"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['cocos'],
    ['season-formats'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 3.1.0'
  }

end
