require 'hoe'
require './lib/football-sources/version.rb'

Hoe.spec 'football-sources' do

  self.version = FootballSources::VERSION

  self.summary = 'football-sources - get football match data (leagues, cups & more) via web pages or web api (json) calls'
  self.description = summary



  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['sportdb-catalogs'],   #, '>= 1.0.0'],
    ['sportdb-writers'],
    ##  footballdata sources
    ['footballdata-api'],
    ['worldfootball'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
